#!/usr/bin/env python3
"""Concatenate lecture slide PDFs into a single PDF.

Merges per-lecture PDFs (generated by Marp) into one combined file,
in the order specified by lecturer.toml.

Usage:
    # From a course directory (uses lecturer.toml for order)
    python -m lecturer.concat_pdf /path/to/course

    # With explicit output path
    python -m lecturer.concat_pdf /path/to/course -o combined.pdf

    # Dry run
    python -m lecturer.concat_pdf /path/to/course --dry-run
"""

import argparse
import sys
from pathlib import Path

from pypdf import PdfReader, PdfWriter

from lecturer.config import list_lectures, load_config


def find_lecture_pdfs(course_dir: Path) -> list[tuple[str, Path]]:
    """Find slide PDFs for all lectures in config order.

    Returns list of (lecture_name, pdf_path) in order.
    """
    lectures = list_lectures(course_dir=course_dir)

    found = []
    for lecture_dir in lectures:
        pdf_path = lecture_dir / "slides" / "slides.pdf"
        if pdf_path.exists():
            found.append((lecture_dir.name, pdf_path))
        else:
            print(f"  Warning: {lecture_dir.name} — no slides.pdf, skipping")

    return found


def concat_pdfs(pdf_paths: list[tuple[str, Path]], output_path: Path) -> None:
    """Merge multiple PDFs into one."""
    writer = PdfWriter()

    for name, pdf_path in pdf_paths:
        writer.append(str(pdf_path))
        page_count = len(writer.pages)
        print(f"  {name}: added ({page_count} pages total)")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer.write(str(output_path))
    writer.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Concatenate lecture slide PDFs into a single PDF.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "course_dir",
        type=Path,
        help="Path to course directory containing lecturer.toml",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="Output PDF path (default: <output_dir>/course-slides.pdf)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be concatenated without creating PDF",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    course_dir = args.course_dir.resolve()
    if not (course_dir / "lecturer.toml").exists():
        print(f"Error: no lecturer.toml found in {course_dir}", file=sys.stderr)
        sys.exit(1)

    config = load_config(course_dir)
    lectures = find_lecture_pdfs(course_dir)

    if not lectures:
        print("Error: no lecture PDFs found.", file=sys.stderr)
        sys.exit(1)

    output_path = args.output or config["output_dir"] / "course-slides.pdf"
    output_path = output_path.resolve()

    total_pages = 0
    print(f"Course:   {config['name']}")
    print(f"Lectures: {len(lectures)}")
    for name, pdf_path in lectures:
        pages = len(PdfReader(str(pdf_path)).pages)
        total_pages += pages
        print(f"  {name}: {pages} pages")

    print(f"\nTotal pages: {total_pages}")
    print(f"Output: {output_path}")

    if args.dry_run:
        print("\nDry run — no PDF created.")
        return

    print("\nMerging...")
    concat_pdfs(lectures, output_path)

    print(f"\nDone: {output_path}")
    print(f"Size: {output_path.stat().st_size / 1024 / 1024:.1f} MB")


if __name__ == "__main__":
    main()
