#!/usr/bin/env python3
"""Concatenate lecture slide PDFs into a single PDF.

Merges per-lecture PDFs (generated by Marp) into one combined file,
in the order specified by arguments or by directory sort order.

Usage:
    # All lectures (auto-discovered from lecturer.toml)
    python -m lecturer.concat_pdf -o output/course-slides.pdf

    # Specific lectures in order
    python -m lecturer.concat_pdf ai-agents-why ai-agents-agents -o output/slides.pdf

    # Dry run
    python -m lecturer.concat_pdf --dry-run
"""

import argparse
import sys
from pathlib import Path

from pypdf import PdfWriter

from lecturer.config import get_content_dir, get_output_dir, list_lectures


def find_lecture_pdfs(
    lecture_names: list[str] | None = None,
    content_dir: Path | None = None,
) -> list[tuple[str, Path]]:
    """Find slide PDFs for the given lectures (or all lectures).

    Returns list of (lecture_name, pdf_path) in order.
    """
    if content_dir is None:
        content_dir = get_content_dir()

    if lecture_names:
        dirs = [(name, content_dir / name) for name in lecture_names]
    else:
        dirs = [(d.name, d) for d in list_lectures(content_dir=content_dir)]

    found = []
    for name, lecture_dir in dirs:
        pdf_path = lecture_dir / "slides" / "slides.pdf"
        if pdf_path.exists():
            found.append((name, pdf_path))
        else:
            print(f"  Warning: {name} — no slides.pdf, skipping")

    return found


def concat_pdfs(pdf_paths: list[tuple[str, Path]], output_path: Path) -> None:
    """Merge multiple PDFs into one."""
    writer = PdfWriter()

    for name, pdf_path in pdf_paths:
        writer.append(str(pdf_path))
        page_count = len(writer.pages)
        print(f"  {name}: added ({page_count} pages total)")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer.write(str(output_path))
    writer.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Concatenate lecture slide PDFs into a single PDF.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "lectures",
        nargs="*",
        help="Lecture names in desired order (default: all, sorted alphabetically)",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="Output PDF path (default: <output_dir>/course-slides.pdf)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be concatenated without creating PDF",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    lectures = find_lecture_pdfs(args.lectures or None)

    if not lectures:
        print("Error: no lecture PDFs found.", file=sys.stderr)
        sys.exit(1)

    output_path = args.output or get_output_dir() / "course-slides.pdf"
    output_path = output_path.resolve()

    total_pages = 0
    print(f"Lectures: {len(lectures)}")
    for name, pdf_path in lectures:
        from pypdf import PdfReader
        pages = len(PdfReader(str(pdf_path)).pages)
        total_pages += pages
        print(f"  {name}: {pages} pages")

    print(f"\nTotal pages: {total_pages}")
    print(f"Output: {output_path}")

    if args.dry_run:
        print("\nDry run — no PDF created.")
        return

    print("\nMerging...")
    concat_pdfs(lectures, output_path)

    print(f"\nDone: {output_path}")
    print(f"Size: {output_path.stat().st_size / 1024 / 1024:.1f} MB")


if __name__ == "__main__":
    main()
